services:
  postgres:
    image: postgres:latest
    container_name: PostgresDB_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_secret
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgresdb:/var/lib/postgresql/data
    networks:
      - appNetwork

  # Visor base de datos
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - appNetwork

  notificaciones:
    build:
      context: ./Backend_Notifications_Express
      dockerfile: Dockerfile
    container_name: notificaciones_server
    env_file: ./.env
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    networks:
      - appNetwork

  proxy:
    build:
      context: ./Backend_Proxy_Express
      dockerfile: Dockerfile
    container_name: proxy_server
    env_file: ./.env
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    networks:
      - appNetwork

  cron:
    build:
      context: ./Backend_Cron_Express
      dockerfile: Dockerfile
    container_name: cron_server
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: "postgresql://root:root_secret@postgres:5432/mydatabase"
    depends_on:
      - postgres
      - redis
    networks:
      - appNetwork

  # nextjs:
  #   build:
  #     context: ./next
  #     dockerfile: Dockerfile
  #   container_name: gvmart_nextjs_container
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     DATABASE_URL: "postgresql://root:root_secret@postgres:5432/mydatabase"
  #   volumes:
  #     - ./next:/app
  #     - /app/node_modules
  #   command: ["npm", "run", "dev"]
  #   depends_on:
  #     - postgres
  #   networks:
  #     - appNetwork

  springboot_app:
    build:
      context: ./Backend_Payments_Springboot
      dockerfile: Dockerfile # Este Dockerfile usa `bootRun --continuous`
    container_name: springboot_app
    ports:
      - "8080:8080"
    volumes:
      - ./Backend_Payments_Springboot:/app # Solo el directorio de la aplicación
      - /app/build # Mantener el directorio de build limpio
      - /app/.gradle # Mantener el caché de dependencias
    environment:
      SPRING_DATASOURCE_URL: "postgresql://root:root_secret@postgres:5432/mydatabase"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root_secret"
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}
    depends_on:
      - postgres
    networks:
      - appNetwork

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    volumes:
      - redis_data:/data
    networks:
      - appNetwork

volumes:
  postgresdb:
  redis_data:


networks:
  appNetwork:
    driver: bridge
