FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY next.config.ts tailwind.config.ts postcss.config.mjs tsconfig.json ./
RUN npm install

COPY prisma ./prisma
RUN npx prisma generate

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]